### ISSUE TITLE
add `require()` test

### ISSUE THREAD

**Issue by Boshen** [oxc-project/monitor-oxc#26]

**Comment by Boshen** [comment]
No possible, it throws a whole bunch of 

```
test at src/main.test.cjs:542:1
✖ is-obj (0.178875ms)
  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/boshen/oxc/monitor-oxc/node_modules/.pnpm/is-obj@3.0.0/node_modules/is-obj/index.js from /Users/boshen/oxc/monitor-oxc/src/main.test.cjs not supported.
  Instead change the require of index.js in /Users/boshen/oxc/monitor-oxc/src/main.test.cjs to a dynamic import() which is available in all CommonJS modules.
      at Object.newLoader [as .js] (/Users/boshen/oxc/monitor-oxc/node_modules/.pnpm/pirates@4.0.6/node_modules/pirates/lib/index.js:61:4)
      at TestContext.<anonymous> (/Users/boshen/oxc/monitor-oxc/src/main.test.cjs:542:32)
      at Test.runInAsyncScope (node:async_hooks:206:9) {
    code: 'ERR_REQUIRE_ESM'
  }```
